// Auto-generated. Do not edit.
// This file is auto-generated by the MakeCode build process.

declare namespace bleMidiTx { // <--- あなたの拡張機能の名前空間に合わせる
    /**
     * Custom Bluetooth MIDI Tx service events
     */
    //% advanced
    const enum MicroBitBleMidiTxServiceEvent {
        MICROBIT_BLE_MIDI_TX_CONNECTED = 1,
        MICROBIT_BLE_MIDI_TX_DISCONNECTED = 2,
    }
}
